[build]
  command = "npm install && npm run build"
  publish = "build"
  base = "frontend"

[functions]
  directory = "/netlify/functions"

[[redirects]]
  from = "/api/node/*"
  to = "/.netlify/functions/node_api/:splat"
  status = 200

[[redirects]]
  from = "/api/python/*"
  to = "/.netlify/functions/python_api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 